entity_unit_map = {
    'width': {'centimetre', 'foot', 'inch', 'metre', 'millimetre', 'yard'},
    'depth': {'centimetre', 'foot', 'inch', 'metre', 'millimetre', 'yard'},
    'height': {'centimetre', 'foot', 'inch', 'metre', 'millimetre', 'yard'},
    'item_weight': {'gram',
        'kilogram',
        'microgram',
        'milligram',
        'ounce',
        'pound',
        'ton'},
    'maximum_weight_recommendation': {'gram',
        'kilogram',
        'microgram',
        'milligram',
        'ounce',
        'pound',
        'ton'},
    'voltage': {'kilovolt', 'millivolt', 'volt'},
    'wattage': {'kilowatt', 'watt'},
    'item_volume': {'centilitre',
        'cubic foot',
        'cubic inch',
        'cup',
        'decilitre',
        'fluid ounce',
        'gallon',
        'imperial gallon',
        'litre',
        'microlitre',
        'millilitre',
        'pint',
        'quart'}
}

unit_variations = {
    'centimetre': {'cm', 'cm', 'centi-meter'},
    'foot': {'ft', 'foot', "'"},
    'inch': {'in', 'inch', '"'},
    'metre': {'m', 'meter', 'metre'},
    'millimetre': {'mm', 'millimeter', 'millimetre'},
    'yard': {'yd', 'yard'},
    
    'gram': {'g', 'gram'},
    'kilogram': {'kg', 'kilogram'},
    'microgram': {'µg', 'microgram'},
    'milligram': {'mg', 'milligram'},
    'ounce': {'oz', 'ounce'},
    'pound': {'lb', 'pound', '#'},
    'ton': {'ton', 'tonne', 't'},
    
    'kilovolt': {'kV', 'kilovolt'},
    'millivolt': {'mV', 'millivolt'},
    'volt': {'V', 'volt'},
    
    'kilowatt': {'kW', 'kilowatt'},
    'watt': {'W', 'watt'},
    
    'centilitre': {'cL', 'centiliter', 'centilitre'},
    'cubic foot': {'ft3', 'ft³', 'cubic foot'},
    'cubic inch': {'in3', 'in³', 'cubic inch'},
    'cup': {'cup', 'C'},
    'decilitre': {'dL', 'deciliter'},
    'fluid ounce': {'fl oz', 'fluid ounce'},
    'gallon': {'gal', 'gallon'},
    'imperial gallon': {'imp gal', 'imperial gallon'},
    'litre': {'L', 'liter', 'litre'},
    'microlitre': {'µL', 'microliter'},
    'millilitre': {'mL', 'milliliter'},
    'pint': {'pt', 'pint'},
    'quart': {'qt', 'quart'}
}

allowed_units = {unit for entity in entity_unit_map for unit in entity_unit_map[entity]}